--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,4 +37,4 @@
     - name: Install local markdownlint-micromark
       run: npm install --no-package-lock ./micromark
     - name: Test with local markdownlint-micromark
-      run: npm test
+      run: npm test